### PR TITLE
Feature/sfw 329 add childfragmentmodule

### PR DESCRIPTION
**Pull request by ubuntudroid**

### CODE REVIEW

**Comment by ubuntudroid** [comment]
> Fragments in viewmodels ?

@aclassen From a technical perspective in our stanwood ViewModels that should be no problem at all. We are not leaking anything here as those are not AndroidViewModels, thus they get destroyed together with the Fragment. This might come in handy when using things like  the Fragment's lifecycle in your ViewModel to subscribe to actions from the UI without having to move too much logic to the Fragment or preventing constant back and forth between ViewModel and Fragment from happening.

**Comment by aclassen** [comment]
> > Fragments in viewmodels ?
> 
> @aclassen From a technical perspective in our stanwood ViewModels that should be no problem at all. We are not leaking anything here as those are not AndroidViewModels, thus they get destroyed together with the Fragment. This might come in handy when using things like the Fragment's lifecycle in your ViewModel to subscribe to actions from the UI without having to move too much logic to the Fragment or preventing constant back and forth between ViewModel and Fragment from happening.

A clear no from my side , even its technical no problem.

**Comment by ubuntudroid** [comment]
> A clear no from my side , even its technical no problem.

@aclassen Care to elaborate? Due to the bidirectional dependency of ViewModel and Fragment?

**Comment by ubuntudroid** [comment]
What would you say if a LifecycleProvider was injected instead?

**Comment by ubuntudroid** [comment]
Closing this PR as after quite a bit discussion we concluded that this feature is usually not really needed (or as with the Fragments in the ViewModels desired) and we want to prevent feature creep here.

**Pull request closed without merging**
